
# A mapping between standard midi instrument names and standard musicxml sound names

# see http://lilypond.org/doc/v2.19/Documentation/notation/midi-instruments
# see http://www.musicxml.com/for-developers/standard-sounds/
midi_sound_map = {
    'accordion': 'keyboard.accordion',
    'acoustic bass': 'pluck.bass.acoustic',
    'acoustic grand': 'keyboard.piano',
    'acoustic guitar (nylon)': 'pluck.guitar.nylon-string',
    'acoustic guitar (steel)': 'pluck.guitar.steel-string',
    'agogo': 'wood.agogo-block',
    'alto sax': 'wind.reed.saxophone.alto',
    'applause': 'effect.applause',
    'bagpipe': 'wind.pipes.bagpipes',
    'banjo': 'pluck.banjo',
    'bass drum': 'drum.bass-drum',
    'baritone sax': 'wind.reed.saxophone.baritone',
    'bassoon': 'brass.trombone',
    'bird tweet': 'effect.bird.tweet',
    'blown bottle': 'wind.flutes.blown-bottle',
    'brass section': 'brass.helicon',
    'breath noise': 'effect.breath',
    'bright acoustic': 'keyboard.piano',
    'celesta': 'keyboard.celesta',
    'cello': 'strings.cello',
    'choir aahs': 'voice.vocals',
    'church organ': 'keyboard.organ',
    'clarinet': 'wind.reed.clarinet',
    'clav': 'keyboard.clavichord',  # ?
    'concertina': 'keyboard.concertina',
    'contrabass': 'strings.contrabass',
    'crash cymbals': 'metal.cymbal.crash',
    'distorted guitar': None,
    'drawbar organ': 'keyboard.organ.drawbar',
    'dulcimer': 'pluck.dulcimer',
    'electric bass (finger)': None,
    'electric bass (pick)': None,
    'electric grand': 'keyboard.electric',  # ?
    'electric guitar (clean)': None,
    'electric guitar (jazz)': None,
    'electric guitar (muted)': None,
    'electric piano 1': 'keyboard.electric',  # ?
    'electric piano 2': 'keyboard.electric',  # ?
    'english horn': 'wind.reed.english-horn',
    'fiddle': 'strings.fiddle',
    'flute': 'wind.flutes.flute',
    'french horn': 'brass.french-horn',
    'fretless bass': 'pluck.bass.fretless',
    'fx 1 (rain)': 'synth.effects.rain',
    'fx 2 (soundtrack)': 'synth.effects.soundtrack',
    'fx 3 (crystal)': 'synth.effects.crystal',
    'fx 4 (atmosphere)': 'synth.effects.atmosphere',
    'fx 5 (brightness)': 'synth.effects.brightness',
    'fx 6 (goblins)': 'synth.effects.goblins',
    'fx 7 (echoes)': 'synth.effects.echoes',
    'fx 8 (sci-fi)': 'synth.effects.sci-fi',
    'glockenspiel': 'pitched-percusstion.glockenspiel',
    'guitar fret noise': 'effect.guitar-fret',
    'guitar harmonics': None,
    'gunshot': 'effect.gunshot',
    'harmonica': 'wind.reed.harmonica',
    'harpsichord': 'keyboard.harpsichord',
    'helicopter': 'effect.helicopter',
    'honky-tonk': 'keyboard.piano.honky-tonk',
    'kalimba': 'pitched-percussion.kalimba',
    'koto': 'pluck.koto',
    'lead 1 (square)': 'synth.tone.square',
    'lead 2 (sawtooth)': 'synth.tone.sawtooth',
    'lead 3 (calliope)': 'wind.flutes.calliope',
    'lead 4 (chiff)': 'pluck.synth.chiff',
    'lead 5 (charang)': 'pluck.synth.charang',
    'lead 6 (voice)': 'voice.synth',
    'lead 7 (fifths)': 'synth.group.fifths',
    'lead 8 (bass+lead)': 'pluck.bass.lead',
    'marimba': 'pitched-percusstion.marimba',
    'melodic tom': 'drum.tom-tom',  # ?
    'music box': 'pitched-percussion.music-box',
    'muted trumpet': 'barss.trumpet',  # problematic
    'oboe': 'wind.reed.oboe',
    'ocarina': 'wind.flutes.ocarina',
    'orchestra hit': 'synth.group.orchestra',  # problematic?
    'orchestral harp': 'pluck.harp',  # ?
    'overdriven guitar': None,
    'pad 1 (new age)': 'synth.pad.polysynth',
    'pad 2 (warm)': 'synth.pad.warm',
    'pad 3 (polysynth)': 'synth.pad.polysynth',
    'pad 4 (choir)': 'synth.pad.choir',
    'pad 5 (bowed)': 'synth.pad.bowed',
    'pad 6 (metallic)': 'synth.pad.metallic',
    'pad 7 (halo)': 'synth.pad.halo',
    'pad 8 (sweep)': 'synth.pad.sweep',
    'pan flute': 'wind.flutes.panpipes',
    'percussive organ': 'voice.percussion',
    'piccolo': 'wind.flutes.flute.piccolo',
    'pizzicato strings': 'pluck.bass',  # problematic
    'recorder': 'wind.flutes.recorder',
    'reed organ': 'keyboard.organ.reed',
    'reverse cymbal': 'metal.cymbal.reverse',
    'rock organ': None,
    'seashore': 'effect.seashore',
    'shakuhachi': 'wind.flutes.shakuhachi',
    'shamisen': 'pluck.shamisen',
    'shanai': 'wind.reed.shenai',
    'sitar': 'pluck.sitar',
    'slap bass 1': 'effect.bass-string-slap',
    'slap bass 2': 'effect.bass-string-slap',  # ?
    'soprano sax': 'wind.reed.saxophone.soprano',
    'steel drums': 'metal.steel-drums',
    'string ensemble 1': 'strings.group',  # ?
    'string ensemble 2': 'strings.group',  # ?
    'synth bass 1': None,
    'synth bass 2': None,
    'synth drum': 'drum.tom-tom.synth',  # ?
    'synth voice': 'voice.synth',
    'synthbrass 1': 'synth.brass.group',  # ?
    'synthbrass 2': 'synth.brass.group',  # ?
    'synthstrings 1': 'strings.group.synth',
    'synthstrings 2': 'strings.group.synth',
    'taiko drum': 'deum.taiko',
    'telephone ring': 'effect.telephone-ring',
    'tenor sax': 'wind.reed.saxophone.tenor',
    'timpani': 'drum.timpani',
    'tinkle bell': 'metal.bells.tinklebell',
    'tremolo strings': None,  # ?
    'trombone': 'brass.trombone',
    'trumpet': 'brass.trumpet',
    'tuba': 'brass.tuba',
    'tubular bells': 'pitched-percussion.tubular-bells',
    'vibraphone': 'pitched-percussion.vibraphone',
    'viola': 'strings.viola',
    'violin': 'strings.violin',
    'voice oohs': 'voice.oo',
    'whistle': 'effect.whistle',
    'woodblock': 'wood.wood-block',
    'xylophone': 'pitched-percussion.xylophone'
}

# General MIDI program numbers (1-128) for each instrument
# See: https://en.wikipedia.org/wiki/General_MIDI#Program_change_events
midi_program_map = {
    'acoustic grand': 1,
    'bright acoustic': 2,
    'electric grand': 3,
    'honky-tonk': 4,
    'electric piano 1': 5,
    'electric piano 2': 6,
    'harpsichord': 7,
    'clav': 8,
    'celesta': 9,
    'glockenspiel': 10,
    'music box': 11,
    'vibraphone': 12,
    'marimba': 13,
    'xylophone': 14,
    'tubular bells': 15,
    'dulcimer': 16,
    'drawbar organ': 17,
    'percussive organ': 18,
    'rock organ': 19,
    'church organ': 20,
    'reed organ': 21,
    'accordion': 22,
    'harmonica': 23,
    'concertina': 24,
    'acoustic guitar (nylon)': 25,
    'acoustic guitar (steel)': 26,
    'electric guitar (jazz)': 27,
    'electric guitar (clean)': 28,
    'electric guitar (muted)': 29,
    'overdriven guitar': 30,
    'distorted guitar': 31,
    'guitar harmonics': 32,
    'acoustic bass': 33,
    'electric bass (finger)': 34,
    'electric bass (pick)': 35,
    'fretless bass': 36,
    'slap bass 1': 37,
    'slap bass 2': 38,
    'synth bass 1': 39,
    'synth bass 2': 40,
    'violin': 41,
    'viola': 42,
    'cello': 43,
    'contrabass': 44,
    'crash cymbals': 120,
    'tremolo strings': 45,
    'pizzicato strings': 46,
    'orchestral harp': 47,
    'timpani': 48,
    'string ensemble 1': 49,
    'string ensemble 2': 50,
    'synthstrings 1': 51,
    'synthstrings 2': 52,
    'choir aahs': 53,
    'voice oohs': 54,
    'synth voice': 55,
    'orchestra hit': 56,
    'trumpet': 57,
    'trombone': 58,
    'tuba': 59,
    'muted trumpet': 60,
    'french horn': 61,
    'brass section': 62,
    'synthbrass 1': 63,
    'synthbrass 2': 64,
    'soprano sax': 65,
    'alto sax': 66,
    'tenor sax': 67,
    'baritone sax': 68,
    'oboe': 69,
    'english horn': 70,
    'bassoon': 71,
    'clarinet': 72,
    'piccolo': 73,
    'flute': 74,
    'recorder': 75,
    'pan flute': 76,
    'blown bottle': 77,
    'shakuhachi': 78,
    'whistle': 79,
    'ocarina': 80,
    'lead 1 (square)': 81,
    'lead 2 (sawtooth)': 82,
    'lead 3 (calliope)': 83,
    'lead 4 (chiff)': 84,
    'lead 5 (charang)': 85,
    'lead 6 (voice)': 86,
    'lead 7 (fifths)': 87,
    'lead 8 (bass+lead)': 88,
    'pad 1 (new age)': 89,
    'pad 2 (warm)': 90,
    'pad 3 (polysynth)': 91,
    'pad 4 (choir)': 92,
    'pad 5 (bowed)': 93,
    'pad 6 (metallic)': 94,
    'pad 7 (halo)': 95,
    'pad 8 (sweep)': 96,
    'fx 1 (rain)': 97,
    'fx 2 (soundtrack)': 98,
    'fx 3 (crystal)': 99,
    'fx 4 (atmosphere)': 100,
    'fx 5 (brightness)': 101,
    'fx 6 (goblins)': 102,
    'fx 7 (echoes)': 103,
    'fx 8 (sci-fi)': 104,
    'sitar': 105,
    'bass drum': 117,
    'banjo': 106,
    'shamisen': 107,
    'koto': 108,
    'kalimba': 109,
    'bagpipe': 110,
    'fiddle': 111,
    'shanai': 112,
    'tinkle bell': 113,
    'agogo': 114,
    'steel drums': 115,
    'woodblock': 116,
    'taiko drum': 117,
    'melodic tom': 118,
    'synth drum': 119,
    'reverse cymbal': 120,
    'guitar fret noise': 121,
    'breath noise': 122,
    'seashore': 123,
    'bird tweet': 124,
    'telephone ring': 125,
    'helicopter': 126,
    'applause': 127,
    'gunshot': 128,
}
